In [1]:
#Question 1
import numpy as np
np.arange(2, 50, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [18]:
#Question 2
n = int(input()) 
mylist=[]
ele=[]
for i in range(0, n): 
    mylist.append(int(input())) 
    ele.append(int(input()))
print("List: ",mylist)  # displaying list
print("List: ",ele)     # displaying list
arr=np.array(mylist) # converting list to array
arr1=np.array(ele)   # converting list to array
print("Array: ",arr)    # displaying array
print("Array: ",arr1)   # displaying array
con=(np.concatenate([arr,arr1]))    #Concatenate arrays
print("Concatenate: ",con)
con.sort()               #Sorting arrays
print('Sorted Array: ',con)


5
1
2
3
4
5
6
7
8
9
10
List:  [1, 3, 5, 7, 9]
List:  [2, 4, 6, 8, 10]
Array:  [1 3 5 7 9]
Array:  [ 2  4  6  8 10]
Concatenate:  [ 1  3  5  7  9  2  4  6  8 10]
Sorted Array:  [ 1  2  3  4  5  6  7  8  9 10]


In [20]:
#Question 3
arr3D = np.array([ [[11, 12, 13, 11], [21, 22, 23, 24], [31, 32, 33, 34]],
                 [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]] ])
print(arr3D)

print('Total Number of elements in 3D Numpy array : ', np.size(arr3D))


[[[11 12 13 11]
  [21 22 23 24]
  [31 32 33 34]]

 [[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]]
Total Number of elements in 3D Numpy array :  24


In [23]:
#Question 4
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]   # np.newaxis to add a new axis
a2.shape

a3 = np.expand_dims(a, axis=1) # np.expand_dims to add an axis at index position 1 
a3.shape


(6, 1)

In [30]:
# Question 5
a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])
np.vstack((a1, a2))   #stack vertically with vstack



array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [31]:
a3 = np.array([[1, 1],[2, 2]])
a4 = np.array([[3, 3],[4, 4]])
np.hstack((a3, a4))   #stack horizontally with hstack

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [34]:
# Question 6
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)


[11 12 13 14 15 16 17 18 19 20]
